# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mygeo', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True)),
                ('satisfaction', models.IntegerField(choices=[(0, 'GOOD'), (1, 'GREAT'), (2, 'AWESOME'), (3, 'PERFECT')], default=0)),
                ('total_money_spent', models.IntegerField(choices=[(0, '$0 - $99'), (1, '$100 - $199'), (2, '$200 - $499'), (3, '$500 - $999'), (4, '$1,000 - $1,999'), (5, '$2,000 - $4,999'), (6, '$5,000 - $9,999'), (7, '$10,000 - $19,999'), (8, '$20,000 - $49,999'), (9, '$50,000 - $99,999'), (10, '$100,000 - $199,999'), (11, '$200,000 - $499,999'), (12, '$500,000 - $999,999')], default=0)),
                ('pricing', models.IntegerField(choices=[(0, 'Budget'), (1, 'AveragePrice'), (2, 'Premium')], default=1)),
                ('on_active_contract', models.BooleanField(default=False)),
                ('is_repeated_customer', models.BooleanField(default=False)),
                ('main_reason_to_reuse', models.IntegerField(choices=[(0, 'LowPrice'), (1, 'Expertise'), (2, 'CustomerService'), (3, 'Availability'), (4, 'Workmanship'), (5, 'Satisfied')], default=5)),
                ('city_serviced', models.ManyToManyField(to='mygeo.City')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.BusinessService')),
            ],
        ),
    ]
