# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mygeo', '0001_initial'),
        ('core', '0008_businessservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True)),
                ('city_serviced', models.ManyToManyField(to='mygeo.City')),
                ('service', models.ManyToManyField(blank=True, to='core.BusinessService')),
            ],
        ),
    ]
