# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessService'),
        ),
    ]
