# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcontact',
            name='IsMultiplePerson',
            field=models.BooleanField(default=True),
        ),
    ]
