# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_recommendedcontact_ismultipleperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedcontact',
            name='IsMultiplePerson',
        ),
    ]
