# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_remove_recommendedcontact_ismultipleperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField(choices=[(0, 'GOOD'), (1, 'GREAT'), (2, 'AWESOME'), (3, 'PERFECT')])),
                ('recommended_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.RecommendedContact')),
            ],
        ),
    ]
