# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170408_2236'),
        ('recommend', '0004_auto_20170408_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ownby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
