# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='total_money_spent',
            field=models.IntegerField(choices=[(0, '$0 - $99'), (1, '$100 - $199'), (2, '$200 - $499'), (3, '$500 - $999'), (4, '$1,000 - $1,999'), (5, '$2,000 - $4,999'), (6, '$5,000 - $9,999'), (7, '$10,000 - $19,999'), (8, '$20,000 - $49,999'), (9, '$50,000 - $99,999'), (10, '$100,000 - $199,999'), (11, '$200,000 - $499,999'), (12, '$500,000 - $999,999')], default=0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='satisfaction',
            field=models.IntegerField(choices=[(0, 'GOOD'), (1, 'GREAT'), (2, 'AWESOME'), (3, 'PERFECT')], default=0),
        ),
    ]
