# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_recommendation_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='pricing',
            field=models.IntegerField(choices=[(0, 'Budget'), (1, 'AveragePrice'), (2, 'Premium')], default=1),
        ),
    ]
