# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_recommendation_has_ongoing_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='main_reason_to_reuse',
            field=models.IntegerField(choices=[(0, 'LowPrice'), (1, 'Expertise'), (2, 'CustomerService'), (3, 'Availability'), (4, 'Workmanship'), (5, 'Satisfied')], default=5),
        ),
    ]
