# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20170422_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='story',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Share your happy story working with them:'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='total_money_spent',
            field=models.IntegerField(choices=[(-1, 'Not Applicable'), (0, '$1 - $99'), (1, '$100 - $199'), (2, '$200 - $499'), (3, '$500 - $999'), (4, '$1,000 - $1,999'), (5, '$2,000 - $4,999'), (6, '$5,000 - $9,999'), (7, '$10,000 - $19,999'), (8, '$20,000 - $49,999'), (9, '$50,000 - $99,999'), (10, '$100,000 - $199,999'), (11, '$200,000 - $499,999'), (12, '$500,000 - $999,999')], default=0, help_text="Select N/A if you don't directly pay (e.g. buyer realtor)", verbose_name='Total purchase so far'),
        ),
    ]
