# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_recommendation_main_reason_to_reuse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='has_ongoing_contract',
            new_name='on_active_contract',
        ),
    ]
