# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_auto_20170423_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='total_money_spent',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_friend',
            field=models.BooleanField(default=False, verbose_name='I learned about this contact from family/friends'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_interview',
            field=models.BooleanField(default=False, verbose_name='I have interviewed alternatives before selecting them'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_network',
            field=models.BooleanField(default=False, verbose_name='I learned about this contact from real estate networking'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name="I am also a customer of this business's competitor"),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_referral',
            field=models.BooleanField(default=False, verbose_name='I learned about this contact from referral'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_replacement',
            field=models.BooleanField(default=False, verbose_name='This replaces my similar contact from before'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_selective',
            field=models.BooleanField(default=False, verbose_name='I have done extensive research on alternatives'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='I have referred this business to many others and they like them too'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_repeated_customer',
            field=models.BooleanField(default=False, verbose_name='I have been a repeated custom for/over many years'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='main_reason_to_reuse',
            field=models.IntegerField(choices=[(0, 'Good price'), (1, 'Expertise'), (2, 'Courteous customer service'), (3, 'Resonsiveness'), (4, 'Quality work'), (5, 'Availiabity'), (6, 'Stress-free experience'), (7, 'Understanding my need'), (8, 'Clarity of communiation')], default=5, verbose_name='I like them primarily for:'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='on_active_contract',
            field=models.BooleanField(default=False, verbose_name='I am an ongoing customer'),
        ),
    ]
