# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_auto_20170408_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend.RecommendedContact'),
        ),
    ]
