# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessservice'),
        ('mygeo', '0001_initial'),
        ('recommend', '0011_auto_20170408_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedcontact',
            name='city_serviced',
        ),
        migrations.RemoveField(
            model_name='recommendedcontact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_contact',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='city_serviced',
            field=models.ManyToManyField(to='mygeo.City'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='service',
            field=models.ManyToManyField(blank=True, to='core.BusinessService'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='RecommendedContact',
        ),
    ]
