# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_auto_20170408_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
