# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_auto_20170423_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='I have already referred this business to many others and they like them too'),
        ),
    ]
