# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessservice'),
        ('recommend', '0015_auto_20170408_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='service',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='service',
            field=models.ManyToManyField(to='core.BusinessService'),
        ),
    ]
