# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessservice'),
        ('recommend', '0018_remove_recommendation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BusinessService'),
        ),
    ]
