# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0019_recommendation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_repeated_customer',
            field=models.BooleanField(default=False),
        ),
    ]
