# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('mygeo', '0001_initial'),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True)),
                ('businessprofile', models.ManyToManyField(blank=True, to='business.BusinessProfile')),
                ('city', models.ManyToManyField(to='mygeo.City')),
                ('city_experience', models.ManyToManyField(blank=True, related_name='city_experience', to='mygeo.City')),
                ('financing_experience', models.ManyToManyField(blank=True, to='experience.FinancingExperience')),
                ('property_type', models.ManyToManyField(blank=True, to='core.PropertyType')),
                ('renovation_experience', models.ManyToManyField(blank=True, to='experience.RenovationExperience')),
                ('tax_experience', models.ManyToManyField(blank=True, to='experience.TaxExperience')),
                ('tenant_experience', models.ManyToManyField(blank=True, to='experience.TenantExperience')),
            ],
        ),
    ]
