# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_experience', models.ManyToManyField(to='core.FinancingExperience')),
                ('property_type', models.ManyToManyField(to='core.PropertyType')),
                ('renovation_experience', models.ManyToManyField(to='core.RenovationExperience')),
                ('tax_experience', models.ManyToManyField(to='core.TaxExperience')),
                ('tenant_experience', models.ManyToManyField(to='core.TenantExperience')),
            ],
        ),
    ]
