# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170408_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='fullname',
        ),
    ]
