# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170408_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(default='', max_length=200),
        ),
    ]
