# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170408_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentexperience',
            name='city_experience',
            field=models.ManyToManyField(blank=True, null=True, to='core.City'),
        ),
    ]
