# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investmentexperience_city_experience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AlterField(
            model_name='investmentexperience',
            name='city_experience',
            field=models.ManyToManyField(blank=True, null=True, to='mygeo.City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
