# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170408_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentexperience',
            name='city_experience',
            field=models.ManyToManyField(blank=True, to='mygeo.City'),
        ),
    ]
