# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentexperience',
            name='city_experience',
        ),
        migrations.RemoveField(
            model_name='investmentexperience',
            name='financing_experience',
        ),
        migrations.RemoveField(
            model_name='investmentexperience',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='investmentexperience',
            name='renovation_experience',
        ),
        migrations.RemoveField(
            model_name='investmentexperience',
            name='tax_experience',
        ),
        migrations.RemoveField(
            model_name='investmentexperience',
            name='tenant_experience',
        ),
        migrations.DeleteModel(
            name='FinancingExperience',
        ),
        migrations.DeleteModel(
            name='InvestmentExperience',
        ),
        migrations.DeleteModel(
            name='RenovationExperience',
        ),
        migrations.DeleteModel(
            name='TaxExperience',
        ),
        migrations.DeleteModel(
            name='TenantExperience',
        ),
    ]
