# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170409_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygeo.City', verbose_name='Residence City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_experience',
            field=models.ManyToManyField(blank=True, related_name='city_experience', to='mygeo.City', verbose_name='I have invested in: (multi-select)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='For other investors to contact you', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='financing_experience',
            field=models.ManyToManyField(blank=True, to='experience.FinancingExperience', verbose_name='I have used following fincancing strateiges: (multi-select)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(help_text='How fellow investors call you', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(blank=True, max_length=200, verbose_name='Self introduction'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='property_type',
            field=models.ManyToManyField(blank=True, to='core.PropertyType', verbose_name='I have invested in: (multi-select)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='renovation_experience',
            field=models.ManyToManyField(blank=True, to='experience.RenovationExperience', verbose_name='I have done these renovations: (multi-select)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role', verbose_name='Primary role in real estate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tax_experience',
            field=models.ManyToManyField(blank=True, to='experience.TaxExperience', verbose_name='I have used following tax strategies: (multi-select)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant_experience',
            field=models.ManyToManyField(blank=True, to='experience.TenantExperience', verbose_name='I have dealt with tenants for: (multi-select)'),
        ),
    ]
