# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_intro'),
        ('business', '0002_auto_20170408_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='ownby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
