# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_city_headquarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='city_headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygeo.City'),
        ),
    ]
