# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170408_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessService',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service',
            field=models.ManyToManyField(blank=True, to='core.BusinessService'),
        ),
    ]
