# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20170422_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessservice',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service',
            field=models.ManyToManyField(to='business.BusinessService'),
        ),
    ]
