# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mygeo', '0001_initial'),
        ('core', '0009_auto_20170408_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_experience', models.ManyToManyField(blank=True, to='mygeo.City')),
                ('financing_experience', models.ManyToManyField(blank=True, to='experience.FinancingExperience')),
                ('property_type', models.ManyToManyField(blank=True, to='core.PropertyType')),
            ],
        ),
        migrations.CreateModel(
            name='RenovationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TenantExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='investmentexperience',
            name='renovation_experience',
            field=models.ManyToManyField(blank=True, to='experience.RenovationExperience'),
        ),
        migrations.AddField(
            model_name='investmentexperience',
            name='tax_experience',
            field=models.ManyToManyField(blank=True, to='experience.TaxExperience'),
        ),
        migrations.AddField(
            model_name='investmentexperience',
            name='tenant_experience',
            field=models.ManyToManyField(blank=True, to='experience.TenantExperience'),
        ),
    ]
