# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financingexperience',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='renovationexperience',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='taxexperience',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tenantexperience',
            options={'ordering': ['name']},
        ),
    ]
